### ISSUE TITLE
RBAC permissions wider than needed

### ISSUE THREAD

**Issue by sarahhodne** [alexellis/registry-creds#16]
**Describe the bug**
The default RBAC permissions requested in `manifest.yaml` (and `config/rbac/`) are much wider than needed. E.g. there's no need to have write permissions (create/delete/patch/update) for namespaces.

**To Reproduce**
1. `kubectl apply -f https://raw.githubusercontent.com/alexellis/registry-creds/master/manifest.yaml`
2. Look at the created `Role` and `ClusterRole`

**Expected behavior**

The default manifest only requests the minimum permissions needed to operate.

**Screenshots or console output**
N/A

**Operating system and version:**
N/A

**List all possible solutions, and your suggested option**
I did a combination of `audit2rbac` on a local kind cluster as well as some code inspection, and came up with this:

``` YAML
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: registry-creds-leader-election-role
  namespace: registry-creds-system
rules:
- apiGroups: [""]
  resourceNames: [8bdecb1a.alexellis.io]
  resources: [configmaps]
  verbs: [create, get, patch, update]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: registry-creds-registry-creds-role
rules:
- apiGroups: [""]
  resources: [namespaces]
  verbs: [get, list, watch]
- apiGroups: [""]
  resources: [secrets]
  verbs: [create, get, list, watch]
- apiGroups: [""]
  resources: [serviceaccounts]
  verbs: [get, list, patch, update, watch]
- apiGroups: [ops.alexellis.io]
  resources: [clusterpullsecrets]
  verbs: [get, list, watch]
```

**Additional context**

I'm using these permissions locally on my cluster, and haven't observed any errors yet (I've tried creating and deleting `ClusterPullSecrets`). I'm happy to open a PR to change things, but I see you want an issue reported first, so here's that.

**Comment by alexellis** [comment]
I agree. I think this was introduced by a community PR. Happy to take a PR @sarahhodne

**Comment by alexellis** [comment]
@sarahhodne thanks for your feedback, did you want to do the PR yourself?

**Comment by developer-guy** [comment]
I'm a volunteer for this issue.

**Comment by sarahhodne** [comment]
I probably won't have time to look at it for a bit, sorry, so feel free to work on this. Here's the roles we actually ended up using and got to work:

```YAML
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: registry-creds
rules:
- apiGroups: [""]
  resources: [namespaces]
  verbs: [get, list, watch]
- apiGroups: [""]
  resources: [secrets]
  verbs: [create, get, list, watch]
- apiGroups: [""]
  resources: [serviceaccounts]
  verbs: [get, list, patch, update, watch]
- apiGroups: [ops.alexellis.io]
  resources: [clusterpullsecrets]
  verbs: [get, list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: registry-creds
rules:
- apiGroups: [""]
  resources: [configmaps, events]
  verbs: [create]
- apiGroups: [""]
  resourceNames: [8bdecb1a.alexellis.io]
  resources: [configmaps]
  verbs: [get, patch, update]
```
