### ISSUE TITLE
Get rid of "registrycreds" suffix from secrets' names

### ISSUE THREAD

**Issue by przemolb** [alexellis/registry-creds#29]
**Is your feature request related to a problem? Please describe.**

**Describe all possible solutions, and which you suggest**

**Describe alternatives and workarounds that you've considered**

**Additional context**

I have just deployed registry-cred - by the way - thank you for this - it is really useful !

I have configured and deployed it successfully. However I have noticed that when I use the following YAML manifest:
```
apiVersion: ops.alexellis.io/v1
kind: ClusterPullSecret
metadata:
  name: docker-registry-1
spec:
  secretRef:
    name: docker-registry-cred
    namespace: ns1
```
it adds "registrycreds" to all secrets' name in each namespace and their name are:
```
docker-registry-1-registrycreds
```
Is it possible to opt out of it ?
